name: RyxoNET
main: com.ryxon.RyxoNet
version: 1.1.2
api-version: 1.21
description: Advanced security plugin enforcing hostname usage, IP whitelisting, and proxy protection
author: SepantaIsHere
discord: livinha9751

commands:
  ryxonet:
    description: Manage RyxoNET settings
    usage: /ryxonet <reload|status|addhost|removehost|listhosts>
    permission: ryxonet.admin

permissions:
  ryxonet.admin:
    description: Allows full access to RyxoNET commands
    default: op